config/routes.rb
Rails.application.routes.draw do
  
  root to: "pages#home"

  devise_for :users, controllers: { registrations: 'users' }

  resources :users do 
    # collection do 
    #   get :fetch_department
    # end
    get "lock", on: :member
    get "unlock", on: :member
  end

  resources :user_divisions, only: %w(new create destroy)


  resources :orders do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :order_coolings do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :frovs do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :assortments do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :divisions do
    collection do 
      post :import
      get :import_file
    end
  end

  # get :export_xls, action: :export_xls, controller: 'orders'
  get 'edit_password_reset', to: 'users#edit_password_reset', as: :edit_password_reset
  patch 'password_reset', to: 'users#password_reset', as: :password_reset
end

app/models/user.rb
class User < ApplicationRecord
  enum type_role: { user: 0, guide: 1, admin: 3, moderator: 4 }

   # Include default devise modules. Others available are:
  # :confirmable, :lockable, :registerable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :rememberable, :validatable, :lockable, 
         :trackable, :timeoutable, :recoverable

  has_one :profile, dependent: :destroy
  has_many :user_divisions, dependent: :destroy
  has_many :divisions, through: :user_divisions

  delegate :full_name, to: :profile
    
  accepts_nested_attributes_for :profile, allow_destroy: true

  default_scope { joins(:profile).order(full_name: :asc) }

  # default_scope { joins(:profile).order(full_name: :asc) }

  # def full_name
  #   self.profile.full_name
  # end

  # def author_of?(resource)
  #   self.id == resource.author_id
  # end
  
  # def executor_of?(resource)
  #   self.id == resource.executor_id
  # end

  # def control_executor_of?(resource)
  #   self.id == resource.control_executor_id
  # end

  # def manager_of?(resource)
  #   self.id == resource.executor.manager_id
  # end

  def self.ransackable_attributes(auth_object = nil)
    ["created_at", "current_sign_in_at", "current_sign_in_ip", "email", "encrypted_password", "failed_attempts", "id", "last_sign_in_at", "last_sign_in_ip", "locked_at", "remember_created_at", "sign_in_count", "type_role", "unlock_token", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["divisions", "profile"]
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :set_user, except: [ :index, :new, :create ]
  
  def index
    # authorize User
    @q = User.includes(:profile).ransack(params[:q])
    @q.sorts = ['full_name asc'] if @q.sorts.empty?
    @count_users = @q.result.count
    @q.sorts = ['profile_full_name asc'] if @q.sorts.empty?
    @pagy, @users = pagy(@q.result(disinct: true), items: 20) 
  end

  def new
    # authorize Users
    #@user = User.new(password: 'UserBlock', password_confirmation: 'UserBlock', locked_at: DateTime.now)
    @user = User.new
    @user.build_profile
  end

  def show
    # authorize @user
  end

  def edit
    # authorize @user
    @user.profile
  end

  def edit_password_reset
   
  end

  def create
    @user = User.new(user_params)    # Not the final implementation!
      # authorize @user   
    respond_to do |format|
      if @user.save
        format.html { redirect_to users_path, notice: t('notice.record_create') }
        format.turbo_stream { flash.now[:success] = t('notice.record_create') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    # authorize @user    
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to users_path, notice: t('notice.record_edit') }
        format.turbo_stream { flash.now[:warning] = t('notice.record_edit') }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def password_reset
    password = params[:user][:password]
    password_confirmation = params[:user][:password_confirmation]
    respond_to do |format|
      unless @user.reset_password(password, password_confirmation)
        format.html { render :edit_password_reset, status: :unprocessable_entity }
      else
        if @user.update_without_password(user_params)
          format.html { redirect_to users_path, notice: t('notice.record_edit') }
          format.turbo_stream { flash.now[:warning] = t('notice.record_edit') }
        else
          format.html { render :edit_password_reset, status: :unprocessable_entity }
        end
      end
    end
  end

  def destroy
    # authorize @user
    if @user.destroy
      respond_to do |format|
        format.html { redirect_to users_path, notice: t('notice.record_destroy') }
        format.turbo_stream { flash.now[:danger] = t('notice.record_destroy') }
      end
      # flash[:success] = "Пользователь удачно удален."
      # redirect_to users_path, status: :see_other
    else
      flash.now[:error] = t('notice.record_destroy_errors')
    end
  end

  def lock
    respond_to do |format|
      if @user.update(locked_at: DateTime.now)
        format.html { redirect_to users_path, notice: t('notice.record_edit') }
        format.turbo_stream { render turbo_stream: turbo_stream.replace(@user) }
        format.turbo_stream { flash.now[:warning] = t('notice.record_edit') }
      else
        format.html { render :lock, status: :unprocessable_entity }
      end
    end
  end

  def unlock
    respond_to do |format|
      if @user.update(locked_at: "")
        format.html { redirect_to users_path, notice: t('notice.record_edit') }
        format.turbo_stream { flash.now[:warning] = t('notice.record_edit') }
      else
        format.html { render :lock, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:email, :type_role, :password, :password_confirmation, 
                                 profile_attributes: [:full_name, :mobile])
  end
end

app/views/users/_control.slim
h5.text-end
  .dropdown
    a#dopdownMenuLink.nav-link aria-expanded="false" aria-haspopup="true" data-bs-toggle="dropdown" href="#"
      i.bi.bi-three-dots-vertical.small
    ul.dropdown-menu.dropdown-menu-end aria-labelledby="dopdownMenuLink"
      - if current_user.admin?
        li
          = link_to t('button.show'), user_path(user), class: "dropdown-item", data: { turbo_frame: "modal_form" }
        li
          = link_to t('button.edit'), edit_user_path(user), class: "dropdown-item", data: { turbo_frame: "modal_form" }
        li
          = link_to t('button.destroy'), user, data: { turbo_confirm: t('notice.confirm'), turbo_method: :delete }, class: "dropdown-item" 
        li
          = link_to t('button.reset_password'), edit_password_reset_path(id: user), class: "dropdown-item", data: { turbo_frame: "modal_form" }

app/views/users/_form.slim
= simple_form_for(@user, html: { class: "row g-2" }) do |f|
  = f.error_notification
  .row
    .col-12.col-md-6
      = f.input :email, required: true, autofocus: true, class: 'form-control form-control-sm', placeholder: "#{t('devise.placeholder.email')}", disabled: !current_user.admin?
    .col-12.col-md-6
      = f.input :type_role, collection: enum_options_for_select(User, :type_role), required: true, class: 'form-control form-control-sm', placeholder: "#{t('devise.placeholder.type_role')}", disabled: !current_user.admin?
  - if f.object.new_record?
    .row 
      .col-12.col-md-6
        = f.input :password, required: true, class: 'form-control form-control-sm', placeholder: "#{t('devise.placeholder.password')}"
        - if @minimum_password_length 
          = content_tag :em, "#{t('devise.shared.minimum_password_length.many', count: @minimum_password_length)}" 
      .col-12.col-md-6
        = f.input :password_confirmation, required: true, class: 'form-control form-control-sm', placeholder: "#{t('devise.placeholder.password_confirmation')}"
  .row
    = f.simple_fields_for :profile, @user.profile || @user.build_profile do |profile|
      = render 'profile_fields', m: profile
  hr
  .row 
    .col-12.col-md-12.text-end
      span.p-2
        = f.submit "#{t('submit.save')}", class: "btn btn-primary"
      span
        = link_to "#{t('submit.cancel')}", users_path, class: "btn btn-primary"

app/views/users/_form_password_reset.slim
= simple_form_for(@user, url: password_reset_path(id: @user), html: { class: "row g-2" }) do |f|
  = f.error_notification
  .row 
    .col-12.col-md-6
      = f.input :password, required: true, class: 'form-control form-control-sm', placeholder: "#{t('devise.placeholder.password')}"
      - if @minimum_password_length 
        = content_tag :em, "#{t('devise.shared.minimum_password_length.many', count: @minimum_password_length)}" 
    .col-12.col-md-6
      = f.input :password_confirmation, required: true, class: 'form-control form-control-sm', placeholder: "#{t('devise.placeholder.password_confirmation')}"
  hr
  .row 
    .col-12.col-md-12.text-end
      span.p-2
        = f.submit "#{t('submit.save')}", class: "btn btn-primary"
      span
        = link_to "#{t('submit.cancel')}", users_path, class: "btn btn-primary"

app/views/users/_user.slim
tr id="#{dom_id(user)}"
  td.text-truncate
    = user.full_name
  / td.text-truncate
  /   = user.store_id
  / td.text-truncate
  /   = user.organization
  td.text-end.px-3
    span.d-block.font-weight-bold
      = render "users/control", user: user

app/views/users/create.turbo_stream.slim
= turbo_stream.prepend "body-users", @user
= render_turbo_stream_flash_messages

app/views/users/destroy.turbo_stream.slim
= turbo_stream.remove @user
= render_turbo_stream_flash_messages

app/views/users/edit.slim
.container
  = turbo_frame_tag "modal_form"
    .modal-header
      h3#modalNewEditLabel.modal-title
        = t('resource.edit') 
      button.btn-close[type="button" data-bs-dismiss="modal" aria-label="Close"]       
    .modal-body
      = render 'users/form', user: @user

app/views/users/edit_password_reset.slim
.container
  = turbo_frame_tag "modal_form"
    .modal-header
      h3#modalNewEditLabel.modal-title
        = t('resource.edit') 
      button.btn-close[type="button" data-bs-dismiss="modal" aria-label="Close"]       
    .modal-body
      = render 'users/form_password_reset'

app/views/users/index.slim
.container
  .row
    .col-12.col-md-12
      = render 'list_users'

app/views/users/new.slim
.container
  = turbo_frame_tag "modal_form"
    .modal-header
      h3#modalNewEditLabel.modal-title
        = t('resource.create')  
      button.btn-close[type="button" data-bs-dismiss="modal" aria-label="Close"]         
    .modal-body
      = render 'users/form', user: @user

app/views/users/password_reset.turbo_stream.slim
= turbo_stream.replace @user
= render_turbo_stream_flash_messages

app/views/users/show.slim
= turbo_frame_tag "modal_form"
  .modal-header
    h4#modalTaskLabel.modal-title.fw-bold.lh-1
      = "#{@user.model_name.human} (#{@user.full_name})"           
    button.btn-close[type="button" data-bs-dismiss="modal" aria-label="Close"]
  .modal-body
    .card.shadow-sm.p-0.mb-3.bg-white.rounded-9
      .card-body
        .row 
          .col-12.text-end.mb-3
            .h6.fst-italic.fw-bold               
              = "#{@user.class.human_attribute_name(:type_role)}: "
              span.fw-normal
                = "#{enum_l(@user, :type_role)}"  
        .row            
          .col-6
            .h6.fst-italic.fw-bold             
              = "#{@user.class.human_attribute_name(:email)}: "
              span.fw-normal
                = @user.email
          .col-4
            .h6.fst-italic.fw-bold               
              = "#{@user.profile.class.human_attribute_name(:mobile)}: "
              span.fw-normal
                = @user.profile.mobile
        .row 
          .col-12.mx-2.mt-3
            .h6.fst-italic.fw-bold
              = "Склады: "  
              = link_to "(Добавить)", new_user_division_path(user_id: @user.id), data: { turbo_frame: "modal_add" }, class: "fw-bold link-success link-offset-3 link-offset-3-hover link-underline link-underline-opacity-0 link-underline-opacity-75-hover small"
            = turbo_frame_tag "user_divisions" 
              - if @user&.user_divisions.present?                
                = render 'user_divisions/user_divisions', resource: @user
            / .col-4.text-center
            /   .h6.fst-italic.fw-bold.text-success.small                  
            /     = "#{@card.class.human_attribute_name(:default_charge_sum)}"
            /   hr.mt-0.text-primary
            /   .row
            /     span.fw-normal.small.mt-0
            /       = @card.default_charge_sum
            / - if @card.locked_at.present?
            /   .row
            /     .col-12.mt-5
            /       .h6.fst-italic.fw-bold.text-danger
            /         = "#{@card.class.human_attribute_name(:locked_at)}:"
            /         span.fw-normal.px-3
            /           =l(@card.locked_at, format: :normal)
    

app/views/users/show.turbo_stream.slim
= turbo_stream.replace @user

app/views/users/update.turbo_stream.slim
= turbo_stream.replace @user
= render_turbo_stream_flash_messages