config/routes.rb
Rails.application.routes.draw do
  
  root to: "pages#home"

  devise_for :users, controllers: { registrations: 'users' }

  resources :users do 
    # collection do 
    #   get :fetch_department
    # end
    get "lock", on: :member
    get "unlock", on: :member
  end

  resources :user_divisions, only: %w(new create destroy)


  resources :orders do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :order_coolings do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :frovs do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :assortments do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :divisions do
    collection do 
      post :import
      get :import_file
    end
  end

  # get :export_xls, action: :export_xls, controller: 'orders'
  get 'edit_password_reset', to: 'users#edit_password_reset', as: :edit_password_reset
  patch 'password_reset', to: 'users#password_reset', as: :password_reset
end

app/models/division.rb
class Division < ApplicationRecord
  has_many :orders, class_name: "Order", foreign_key: "store_id", dependent: :destroy
  has_many :assortments, class_name: "Assortment", foreign_key: "store_id", dependent: :destroy
  has_many :user_divisions, dependent: :destroy

  scope :except_user_divisions, ->(divisions_ids) { where.not(id: divisions_ids) }

  def self.ransackable_attributes(auth_object = nil)
    ["name", "store_id", "organization", "created_at", "id", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["orders"]
  end

  def self.import(file)
    accessible_attributes = ['id','name', 'organization']

    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      division = find_by_id(row["id"]) || new
      division.attributes = row.to_hash.slice(*accessible_attributes)
      division.save
    end
  end
end

app/controllers/divisions_controller.rb
class DivisionsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_division, except: [ :index, :new, :create, :import, :import_file ]
  before_action :set_divisions, only: [ :index ]

  def index; end

  def new
    # authorize Division
    @division = Division.new
  end

  def show; end

  def edit; end

  def create
    @division = Division.new(division_params) 
    # authorize @division  
    respond_to do |format|
      if @division.save
        format.html { redirect_to divisions_path, notice: t('notice.record_create') }
        format.turbo_stream { flash.now[:success] = t('notice.record_create') }
      else
        format.html { render :new, status: :unprocessable_entity }
      end
    end
  end

  def update
    # authorize @division   
    respond_to do |format|
      if @division.update(division_params)
        format.html { redirect_to divisions_path, notice: t('notice.record_edit') }
        format.turbo_stream { flash.now[:warning] = t('notice.record_edit') }
      else
        format.html { render :edit, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    # authorize @division
    if @division.destroy
      respond_to do |format|
        format.html { redirect_to divisions_path, notice: t('notice.record_destroy') }
        format.turbo_stream { flash.now[:danger] = t('notice.record_destroy') }
      end
    else
      flash.now[:error] = t('notice.record_destroy_errors')
    end
  end

  def import
    if params[:file].present?
      Division.import(params[:file])
      set_divisions
      flash.now[:notice] = t('notice.record_imported')
    else
      flash.now[:error] = t('notice.record_imported_error')
    end
    redirect_to divisions_path unless turbo_frame_request?
  end

  def import_file; end

  private

  def set_division
    @division = Division.find(params[:id])
  end

  def set_divisions
    # authorize Division
    @q = Division.ransack(params[:q])
    @q.sorts = ['name asc' ] if @q.sorts.empty?
    # @divisions = @q.result(disinct: true)
    @pagy, @divisions = pagy(@q.result(disinct: true)) 
  end

  def division_params
    params.require(:division).permit(:store_id, :name, :organization)
  end
end

app/views/divisions/_control.slim
h5.text-end
  .dropdown
    a#dopdownMenuLink.nav-link aria-expanded="false" aria-haspopup="true" data-bs-toggle="dropdown" href="#"
      i.bi.bi-three-dots-vertical.small
    ul.dropdown-menu.dropdown-menu-end aria-labelledby="dopdownMenuLink"
      li
        = link_to t('button.show'), division_path(division), class: "dropdown-item", data: { turbo_frame: "modal_form" }

      - if current_user.admin?
        li
          = link_to t('button.edit'), edit_division_path(division), class: "dropdown-item", data: { turbo_frame: "modal_form" }
        li
          = link_to t('button.destroy'), division, data: { turbo_confirm: t('notice.confirm'), turbo_method: :delete }, class: "dropdown-item" 

app/views/divisions/_division.slim
tr id="#{dom_id(division)}"
  td.text-truncate
    = division.name
  / td.text-truncate
  /   = division.store_id
  td.text-truncate
    = division.organization
  td.text-end.px-3
    span.d-block.font-weight-bold
      = render "divisions/control", division: division

app/views/divisions/_list_divisions.slim
.row
  .col-12.col-md-12.text-end
    - if current_user&.admin? || current_user&.moderator?
      = link_to "#{t('button.import')}", import_file_divisions_path, class: "btn btn-outline-primary btn-sm mx-4", data: { turbo_frame: "modal_form" }
      = link_to "#{t('button.new')}", new_division_path, class: "btn btn-outline-success btn-sm", data: { turbo_frame: "modal_form" }
  .row.mt-2.p-0.mx-0
    = render 'search_form'
  .row 
    = "Кол-во записей: #{Division.count}"
  hr.mb-0
.row
  .contetnt-divisions[data-controller="my-loading" data-action="turbo:before-fetch-request@document->my-loading#displayDivisionsLoading turbo:before-fetch-response@document->my-loading#displayContentDivisions"]
    = render 'shared/loading_data' 
    .col-12.col-md-12.mt-3
      = turbo_frame_tag "divisions"
        .container
          .catalog
            .fixed-header
              table.table
                thead.table-primary.thead
                  tr
                    th
                      / = sort_link(@q, :release_at, class: 'd-block text-decoration-none text-dark')
                      = t("#{@divisions.model.human_attribute_name(:name)}") 
                    / th
                    /   / = sort_link(@q, :owner_card, class: 'd-block text-decoration-none text-dark')
                    /   = t("#{@divisions.model.human_attribute_name(:store_id)}")
                    th
                      / = sort_link(@q, :balance, class: 'd-block text-decoration-none text-dark')
                      = t("#{@divisions.model.human_attribute_name(:organization)}")
                    
                    th.text-end.font-weight-bold.px-3
                      i.bi.bi-grip-vertical       
                tbody#body-divisions[data-my-loading-target="contentDivisions"]
                  = render @divisions
          .mt-3.stiky-bottom
            == pagy_bootstrap_nav(@pagy).html_safe if @pagy.pages > 1

app/views/divisions/_search_form.slim
= search_form_for (@q), builder: SimpleForm::FormBuilder do |f|
  .col-4.float-end
    = f.input :name_or_organization_cont_any, label: false, placeholder: "Поиск", autofocus: true, input_html: { class: 'form-control form-control-sm' }

app/views/divisions/create.turbo_stream.slim
= turbo_stream.prepend "body-divisions", @division
= render_turbo_stream_flash_messages

app/views/divisions/destroy.turbo_stream.slim
= turbo_stream.remove @division
= render_turbo_stream_flash_messages

app/views/divisions/edit.slim
.container
  = turbo_frame_tag "modal_form"
    .modal-header
      h3#modalNewEditLabel.modal-title
        = t('resource.edit') 
      button.btn-close[type="button" data-bs-dismiss="modal" aria-label="Close"]       
    .modal-body
      = render 'divisions/form', division: @division

app/views/divisions/import.turbo_stream.slim
= turbo_stream.replace 'list_divisions', partial: "divisions/list_divisions"
= render_turbo_stream_flash_messages

app/views/divisions/import_file.slim
.container
  = turbo_frame_tag "modal_form"
    .modal-header
      h3#modalNewEditLabel.modal-title
        = t('resource.load') 
      button.btn-close[type="button" data-bs-dismiss="modal" aria-label="Close"]       
    .modal-body
      = form_with url: import_divisions_path, method: :post do |f|
        .row 
          .col-12
            = f.file_field :file, class: 'form-control'
        .row
          .col-12.text-end.mt-4
            = f.submit "#{t('submit.load')}", class: "btn btn-outline-primary"

app/views/divisions/index.slim
.container
  .row
    .col-12.col-md-12
      #list_divisions
        = render 'list_divisions'

app/views/divisions/new.slim
.container
  = turbo_frame_tag "modal_form"
    .modal-header
      h3#modalNewEditLabel.modal-title
        = t('resource.create')  
      button.btn-close[type="button" data-bs-dismiss="modal" aria-label="Close"]         
    .modal-body
      = render 'divisions/form', division: @division

app/views/divisions/show.slim
/ = turbo_frame_tag "modal_form"
/   .modal-header
/     h4#modalTaskLabel.modal-title.fw-bold.lh-1
/       = "#{@card.model_name.human}"           
/     button.btn-close[type="button" data-bs-dismiss="modal" aria-label="Close"]
/   .modal-body
/     .card.shadow-sm.p-0.mb-3.bg-white.rounded-9
/       .card-body               
/         .col-12
/           .h5.fst-italic.fw-bold.text-muted
/             = "#{@card.class.human_attribute_name(:owner_card)}: "
/             span.fw-normal
/               = @card.owner_card
/           hr.p-0.mt-0
/           - if current_user.admin?
/             .row.mx-1            
/               .col-12
/                 .h6.fst-italic.fw-bold.text-muted
/                   = "#{@card.class.human_attribute_name(:code_card)}:"
/                   span.fw-normal.px-3
/                     = @card.code_card
/           .row.mt-4
/             .col-4.text-center
/               .h6.fst-italic.fw-bold.text-success.small               
/                 = "#{@card.class.human_attribute_name(:release_at)}"
/               hr.mt-0.text-primary
/               .row
/                 span.fw-normal.small
/                   = l(@card.release_at, format: :normal)
/             .col-4.text-center
/               .h6.fst-italic.fw-bold.text-success.small                 
/                 = "#{@card.class.human_attribute_name(:balance)}"
/               hr.mt-0.text-primary
/               .row
/                 span.fw-normal.small
/                   = @card.balance
/             .col-4.text-center
/               .h6.fst-italic.fw-bold.text-success.small                  
/                 = "#{@card.class.human_attribute_name(:default_charge_sum)}"
/               hr.mt-0.text-primary
/               .row
/                 span.fw-normal.small.mt-0
/                   = @card.default_charge_sum
/             - if @card.locked_at.present?
/               .row
/                 .col-12.mt-5
/                   .h6.fst-italic.fw-bold.text-danger
/                     = "#{@card.class.human_attribute_name(:locked_at)}:"
/                     span.fw-normal.px-3
/                       =l(@card.locked_at, format: :normal)
    

app/views/divisions/show.turbo_stream.slim
= turbo_stream.replace @division

app/views/divisions/update.turbo_stream.slim
= turbo_stream.replace @division
= render_turbo_stream_flash_messages