config/routes.rb
Rails.application.routes.draw do
  
  root to: "pages#home"

  devise_for :users, controllers: { registrations: 'users' }

  resources :users do 
    # collection do 
    #   get :fetch_department
    # end
    get "lock", on: :member
    get "unlock", on: :member
  end

  resources :user_divisions, only: %w(new create destroy)


  resources :orders do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :order_coolings do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :frovs do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :assortments do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :divisions do
    collection do 
      post :import
      get :import_file
    end
  end

  # get :export_xls, action: :export_xls, controller: 'orders'
  get 'edit_password_reset', to: 'users#edit_password_reset', as: :edit_password_reset
  patch 'password_reset', to: 'users#password_reset', as: :password_reset
end

app/views/pages/home.slim
.container 
  .row.justify-content-center.align-items-center
      .col-12.col-md-6.mt-5
        .card.shadow.p-3.mb-5.bg-white.rounded
          .card-header.bg-transparent.p-2
            .card-title.h5.font-weight-bold.text-center
              = t('resource.select')
          .card-body.pb-0.m-4.text-center
            .col-12
              = link_to t('orders.title'), orders_path, class: "btn btn-outline-success m-2"
            .col-12
              = link_to t('order_coolings.title'), order_coolings_path, class: "btn btn-outline-success m-2"
            .col-12
              = link_to t('frovs.title'), frovs_path, class: "btn btn-outline-success m-2"  
            .col-12
              = link_to t('assortments.title'), assortments_path, class: "btn btn-outline-success m-2" 
              