config/routes.rb
Rails.application.routes.draw do
  
  root to: "pages#home"

  devise_for :users, controllers: { registrations: 'users' }

  resources :users do 
    # collection do 
    #   get :fetch_department
    # end
    get "lock", on: :member
    get "unlock", on: :member
  end

  resources :user_divisions, only: %w(new create destroy)


  resources :orders do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :order_coolings do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :frovs do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :assortments do
    collection do 
      post :import
      get  :import_file
    end
  end

  resources :divisions do
    collection do 
      post :import
      get :import_file
    end
  end

  # get :export_xls, action: :export_xls, controller: 'orders'
  get 'edit_password_reset', to: 'users#edit_password_reset', as: :edit_password_reset
  patch 'password_reset', to: 'users#password_reset', as: :password_reset
end

app/models/order_cooling.rb
class OrderCooling < ApplicationRecord
  belongs_to :division, class_name: "Division", foreign_key: "store_id", optional: true

  default_scope { joins(:division).order(name: :asc, provider: :asc, product: :asc) }

  scope :provider, -> { where.not(provider: nil).reorder(:provider).distinct.pluck(:provider) }
  scope :product_group, -> { where.not(product_group: nil).reorder(:product_group).distinct.pluck(:product_group) }
  scope :product, -> { where.not(product: nil).reorder(:product).distinct.pluck(:product) }
  scope :availability_order, -> { where.not(availability_order: nil).reorder(:availability_order).distinct.pluck(:availability_order) }
  scope :to_order, -> { where.not(to_order: nil).reorder(:to_order).distinct.pluck(:to_order) }

  scope :current_divisions, ->(divisions_ids) { where(store_id: divisions_ids)}

  def self.ransackable_attributes(auth_object = nil)

    ["availability_order", "average_sales", "cal_day_order", "created_at", 
      "day_store", "id", "next_order", "product", 
      "product_group", "provider", "quantum", "remainder", "required", 
      "sales", "store_id", "store", "to_order", "colored", "updated_at"]
  end

  def self.ransackable_associations(auth_object = nil)
    ["division"]
  end

  def self.import(file)
    accessible_attributes = [ 'store_id', 'provider', 
                              'product_group', 'required', 'product', 'day_store', 'sales', 
                              'remainder', 'average_sales', 'to_order', 'quantum', 
                              'availability_order', 'next_order', 'cal_day_order', 'colored']

    spreadsheet = open_spreadsheet(file)
    header = spreadsheet.row(1)
    (2..spreadsheet.last_row).each do |i|
      row = Hash[[header, spreadsheet.row(i)].transpose]
      order_cooling = new
      order_cooling.attributes = row.to_hash.slice(*accessible_attributes)
      order_cooling.save
    end
  end
  
end

app/controllers/order_coolings_controller.rb
class OrderCoolingsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_order_coolings, only: [ :index ]
  
  def index   
    # # authorize Division 
    respond_to do |format|
      format.html
      format.xlsx do
        render xlsx: 'order_coolings', template: 'order_coolings/export_xls'
      end
    end
  end

  def import
    if params[:file].present?
      OrderCooling.delete_all
      OrderCooling.import(params[:file])
      
      flash.now[:notice] = t('notice.record_imported')
      set_order_coolings
    else
      flash.now[:error] = t('notice.record_imported_error')
    end
    # redirect_to orders_path unless turbo_frame_request?
  end

  def import_file; end

  def set_order_coolings
    if current_user.admin? || current_user.moderator? || current_user.guide?
      @q = OrderCooling.includes(:division).ransack(params[:q])
      @order_cooling_divisions = Division.all
    else
      @q = OrderCooling.includes(:division).current_divisions(current_user.divisions.pluck(:id)).ransack(params[:q])
      @order_cooling_divisions = current_user.divisions
    end
    @order_cooling_providers = @q.result.provider
    @order_cooling_products = @q.result.product
    @oorder_cooling_product_groups = @q.result.product_group
    @availability_order_coolings = @q.result.availability_order
    @to_order_coolings = @q.result.to_order
    @count_order_coolings = @q.result.count
    # @xls = @q.result(disinct: true)
    @q.sorts = ['division_name asc', 'provider asc', 'product asc'] if @q.sorts.empty?
    @xls = @q.result(disinct: true)
    @pagy, @order_coolings = pagy(@q.result(disinct: true), limit: 25)
  end
end

app/views/order_coolings/_list_order_coolings.slim
.row
  .col-6.col-md-6.fw-bold.text-muted.mt-2.mb-0.pb-0
    - if @order_coolings.present?
      = "Кол-во записей: #{@count_order_coolings} (Актуально на: #{l(@order_coolings.last.created_at, format: :small)})"
    - else 
      = "Кол-во записей: #{@count_order_coolings}"
  .col-6.col-md-6.text-end      
    button.btn.btn-outline-success.btn-sm type="button" data-bs-toggle="offcanvas" data-bs-target="#staticBackdropOrderCooling" aria-controls="staticBackdropOrderCooling"
      i.bi.bi-funnel-fill
      | Фильтр
    - if params[:q].present?
      = link_to t('submit.clear'), request.path, class: 'btn btn-outline-secondary btn-sm mx-1'
      / = link_to t('button.export_xls'), export_xls_path(format: "xlsx"), class: 'btn btn-outline-warning btn-sm mx-1'
      = link_to t('button.export_xls'), order_coolings_path(q: request.params[:q], format: 'xlsx'), class: 'btn btn-outline-warning btn-sm mx-1'
    - if current_user&.admin? || current_user&.moderator?
      = link_to "#{t('button.import')}", import_file_order_coolings_path, class: "btn btn-outline-primary btn-sm mx-4", data: { turbo_frame: "modal_form" }
  / .row.mt-2.p-0.mx-0
  /   = render 'search_form'
  hr.mb-0.mt-2
.row
  .contetnt-order-coolings.px-0.ps-0[data-controller="my-loading" data-action="turbo:before-fetch-request@document->my-loading#displayOrderCoolingsLoading turbo:before-fetch-response@document->my-loading#displayContentOrderCoolings"]
    = render 'shared/loading_data' 
    .col-12.col-md-12.mt-2
      = turbo_frame_tag "order_coolings"
        / .row
        /   == pagy_bootstrap_nav(@pagy)
        .container-fluid.sticky-top.p-0
          .fixed-header.small.small
            table.table.table-bordered.table-sm
              thead.table-primary.align-middle.thead
                tr
                  th.small
                    = sort_link(@q, 'division_name', class: 'd-block text-decoration-none text-dark')
                      = "Склад"
                      = show_icon_filter(:store_id_in)
                  th.small
                    = sort_link(@q, :provider, class: 'd-block text-decoration-none text-dark')
                      = "Поставщик" 
                      = show_icon_filter(:provider_in)                      
                  th.small
                    = sort_link(@q, :product, class: 'd-block text-decoration-none text-dark')
                      = "Наименование"
                  th.small.text-center
                    = sort_link(@q, :required, class: 'd-block text-decoration-none text-dark')
                      = "Обязат."
                  th.small.text-center
                    = sort_link(@q, :day_store, class: 'd-block text-decoration-none text-dark')
                      = "К-во дн. присуст."
                  th.small.text-center
                    = sort_link(@q, :sales, class: 'd-block text-decoration-none text-dark')
                      = "Продажи"
                  th.small.text-center
                    = sort_link(@q, :remainder, class: 'd-block text-decoration-none text-dark')
                      = "Остат."
                  th.small.text-center
                    = sort_link(@q, :average_sales, class: 'd-block text-decoration-none text-dark')
                      = "Сред.дн. прод."
                  th.small.text-center.text-nowrap
                    = sort_link(@q, :to_order, class: 'd-block text-decoration-none text-dark')
                      = "К зак."
                      = show_icon_filter(:to_order_in)                   
                  th.small.text-center
                    = sort_link(@q, :quantum, class: 'd-block text-decoration-none text-dark')
                      = "Квант"                    
                  th.small.text-center.text-nowrap
                    = sort_link(@q, :availability_order, class: 'd-block text-decoration-none text-dark')
                      = "Нал. зак."
                      = show_icon_filter(:availability_order_in)                
                  th.small.text-center
                    = sort_link(@q, :next_order, class: 'd-block text-decoration-none text-dark')
                      = "След. зак."
                  th.small.text-center
                    = sort_link(@q, :cal_day_order, class: 'd-block text-decoration-none text-dark')
                      = "Расч. дн."                                                                
                  
                  / th.text-end.font-weight-bold.px-3
                  /   i.bi.bi-grip-vertical       
              tbody#body-order-coolings[data-my-loading-target="contentOrderCoolings"]
                = render @order_coolings
          
                / .row.fixed-bottom

        .mt-2.stiky-bottom
          == pagy_bootstrap_nav(@pagy).html_safe if @pagy.pages > 1

app/views/order_coolings/_navigator.slim
aside
  nav#bd-docs-nav aria-label=t('order_coolings.title')
    .row
      .col-12
        h4 
          = t('orders.title') 
        = render 'order_coolings/search_form'  

app/views/order_coolings/_order_cooling.slim
tr id="#{dom_id(order_cooling)}"
  td.small
    = order_cooling.division&.name
  td.small
    = order_cooling.provider
  td.small.
    = order_cooling.product
  td.small.text-end
    = order_cooling.required
  td.small.text-end
    = order_cooling.day_store
  td.small.text-end
    = order_cooling.sales
  td.small.text-end
    = order_cooling.remainder
  td.small.text-end
    = number_with_precision(order_cooling.average_sales, precision: 1)
  td.small.text-end
    = order_cooling.to_order
  td.small.text-end
    = order_cooling.quantum     
  td.small.text-end
    = order_cooling.availability_order
  td.small.text-end
    = order_cooling.next_order
  td.small.text-end
    = order_cooling.cal_day_order

  / td.text-end.px-3
  /   span.d-block.font-weight-bold
  /     = render "divisions/control", division: division

app/views/order_coolings/_search_form.slim
.container-fluid
  = search_form_for (@q), builder: SimpleForm::FormBuilder do |f|
    .row
      .col-12.text-end
        = f.submit t('submit.search'), class: 'btn btn-sm btn-outline-primary mx-1'
        = link_to t('submit.clear'), request.path, class: 'btn btn-sm btn-outline-primary mx-1'
    .row
      .col-12
        = f.input :store_id_in, collection: @order_cooling_divisions, label_method: :name, value_method: :id, label: "Склад", input_html: { id: "order-store-select", class: "form-control form-control-sm text-truncate", multiple: "multiple", data: { controller: "select2", placeholder: t('simple_form.prompt'), theme: 'bootstrap-5' } }
    .row
      .col-12
        = f.input :provider_in, collection: @order_cooling_providers, label: "Поставщик", input_html: { id: "order-provider-select", class: "form-control form-control-sm", multiple: "multiple", data: { controller: "select2", placeholder: t('simple_form.prompt'), theme: 'bootstrap-5' } }
    / .row
    /   .col-12
    /     = f.input :product_cont_any, collection: @order_products, label: "Наименование", input_html: { id: "order-product-select", class: "m-0 form-control form-control-sm", multiple: "multiple", data: { controller: "select2", placeholder: t('simple_form.prompt'), theme: 'bootstrap-5' } }
    .row
      .col-12
        = f.input :product_group_in, collection: @order_cooling_product_groups, label: "Группа", input_html: { id: "order-product-group-select", class: "form-control form-control-sm", multiple: "multiple", data: { controller: "select2", placeholder: t('simple_form.prompt'), theme: 'bootstrap-5' } }
    .row  
      .col-12
        = f.input :availability_order_in, collection: @availability_order_coolings, label: "Наличие заказа", input_html: { id: "order-availability-order-select", class: "form-control form-control-sm", multiple: "multiple", data: { controller: "select2", placeholder: t('simple_form.prompt'), theme: 'bootstrap-5' } }
    .row
      .col-12
        = f.input :to_order_in, collection: @to_order_coolings, label: "К заказу", input_html: { id: "order-to-order-select", class: "form-control form-control-sm", multiple: "multiple", data: { controller: "select2", placeholder: t('simple_form.prompt'), theme: 'bootstrap-5' } }
  / .row
  /   .col-12
  /     = f.input :store_eq, collection: Division.all, label_method: :full_name, value_method: :full_name, label: "Склад", input_html: { class: "form-control form-control-sm" }
  / .row
  /   .col-12
  /     = f.input :provider_eq, collection: Order.all, label_method: :full_name, value_method: :id, label: "Поставщик", input_html: { class: "form-control form-control-sm" }
  / .row
  /   .col-12
  /     = f.input :division_id_in, collection: Division.all, label_method: :name, value_method: :id, label: "Подразделение", input_html: { id: "single-select-division-task-search", class: "form-control form-control-sm", multiple: "multiple", data: { controller: "select2", placeholder: t('simple_form.prompt'), theme: 'bootstrap-5' } }
  / .row
  /   .col-12
  /     = f.input :sub_categories_id_in, collection: SubCategory.all, label_method: :name, value_method: :id, label: "Проделанная работа", input_html: { id: "single-select-sub_category-task-search", class: "form-control form-control-sm", multiple: "multiple", data: { controller: "select2", placeholder: t('simple_form.prompt'), theme: 'bootstrap-5' } }
  / .row
  /   .col-12
  /     = f.input :status_eq,  collection: Task.statuses.map {|k, v| [t("activerecord.enums.task.statuses.#{k}"), v]}, label: "Статус заявки", input_html: { class: "form-control form-control-sm" }  
  / .row
  /   .col-12.text-end
  /     = f.submit t('submit.search'), class: 'btn btn-outline-primary mx-1'
  /     = link_to t('submit.clear'), request.path, class: 'btn btn-outline-primary mx-1'

app/views/order_coolings/import.turbo_stream.slim
= turbo_stream.replace 'list_order_coolings', partial: "order_coolings/list_order_coolings"
= turbo_stream.replace 'order_coolings_search', partial: "order_coolings/search_form"
= render_turbo_stream_flash_messages

app/views/order_coolings/import_file.slim
.container
  = turbo_frame_tag "modal_form"
    .modal-header
      h3#modalNewEditLabel.modal-title
        = t('resource.load') 
      button.btn-close[type="button" data-bs-dismiss="modal" aria-label="Close"]       
    .modal-body
      = form_with url: import_order_coolings_path, method: :post do |f|
        .row 
          .col-12
            = f.file_field :file, class: 'form-control'
        .row
          .col-12.text-end.mt-4
            = f.submit "#{t('submit.load')}", class: "btn btn-outline-primary"

app/views/order_coolings/index.slim
.container-fluid
  .row
    = render "shared/offcanvas_order_cooling"
  .col-11.col-md-12.col-lg-12
    #list_orders
      = render 'list_order_coolings'